### ISSUE TITLE
Building the Rainmaker Agent Firmware

### ISSUE THREAD

**Issue by jaimeskatz** [m5stack/Core2-for-AWS-IoT-EduKit#76] opened 2021-09-30 18:18 UTC
Pasted into the terminal the following command (per the online instructions):

     pio run --environment core2foraws

In the Getting-Started project. I'm getting the following error:

     file failed to open for reading (No such file or directory):

    /Core2-for-AWS-IoT-EduKit/Getting-Started/.pio/build/core2foraws/x509_crt_bundle

Should I be?

Thanks,
Jaime Katz

**Comment by rashedtalukder** [comment] 2021-09-30 23:53
This is a duplicate of: https://github.com/m5stack/Core2-for-AWS-IoT-EduKit/issues/75 . Please follow that issue while I triage that issue.

Closing this issue.

**Closed by rashedtalukder** 2021-09-30 23:53 UTC
